platform: linux
image_resource:
  type: docker-image
  source: { repository: "corvyx/i-neda-golang", tag: 1.9 }
inputs:
- name: testpipeline
outputs:
- name: artifact
run:
  dir: testpipeline
  path: ci/scripts/compile.sh
