platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 'alpine'

inputs:
- name: jblackman-git-resource

run:
  path: go
  args: [ test ]
  dir: jblackman-git-resource

