resources:
- name: testpipeline
  type: git
  source:
    uri: https://github.com/jblackman/testpipeline.git
    branch: master

- name: demo-image
  type: docker-image
  source:
    repository: "br-dev-tote01:5000/joedemo"
    insecure_registries: [ "br-dev-tote01:5000" ]

jobs:
- name: unit_test
  plan:
  - get: testpipeline
    trigger: true
  - task: unit_test
    file: testpipeline/ci/tasks/unit_test.yml

- name: compile
  plan:
  - get: testpipeline
    trigger: true
    passed: [ unit_test ]
  - task: compile
    file: testpipeline/ci/tasks/compile.yml

- name: deploy
  plan:
  - get: testpipeline
    trigger: true
    passed: [ compile ]
  - task: compile
    file: testpipeline/ci/tasks/compile.yml
  - put: demo-image
    params:
      build: artifact
      dockerfile: artifact/ci/Dockerfile
      tag_as_latest: true
